// Code generated by entc, DO NOT EDIT.

package unsavedpostthumbnail

import (
	"time"
)

const (
	// Label holds the string label denoting the unsavedpostthumbnail type in the database.
	Label = "unsaved_post_thumbnail"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWidth holds the string denoting the width field in the database.
	FieldWidth = "width"
	// FieldHeight holds the string denoting the height field in the database.
	FieldHeight = "height"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUnsavedPost holds the string denoting the unsaved_post edge name in mutations.
	EdgeUnsavedPost = "unsaved_post"
	// Table holds the table name of the unsavedpostthumbnail in the database.
	Table = "unsaved_post_thumbnails"
	// UnsavedPostTable is the table the holds the unsaved_post relation/edge.
	UnsavedPostTable = "unsaved_post_thumbnails"
	// UnsavedPostInverseTable is the table name for the UnsavedPost entity.
	// It exists in this package in order to avoid circular dependency with the "unsavedpost" package.
	UnsavedPostInverseTable = "unsaved_posts"
	// UnsavedPostColumn is the table column denoting the unsaved_post relation/edge.
	UnsavedPostColumn = "unsaved_post_thumbnail"
)

// Columns holds all SQL columns for unsavedpostthumbnail fields.
var Columns = []string{
	FieldID,
	FieldWidth,
	FieldHeight,
	FieldHash,
	FieldURL,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "unsaved_post_thumbnails"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"unsaved_post_thumbnail",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// HashValidator is a validator for the "hash" field. It is called by the builders before save.
	HashValidator func(string) error
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
