// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"devlog/ent/postattachment"
	"devlog/ent/predicate"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostAttachmentDelete is the builder for deleting a PostAttachment entity.
type PostAttachmentDelete struct {
	config
	hooks    []Hook
	mutation *PostAttachmentMutation
}

// Where appends a list predicates to the PostAttachmentDelete builder.
func (pad *PostAttachmentDelete) Where(ps ...predicate.PostAttachment) *PostAttachmentDelete {
	pad.mutation.Where(ps...)
	return pad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pad *PostAttachmentDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pad.hooks) == 0 {
		affected, err = pad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PostAttachmentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pad.mutation = mutation
			affected, err = pad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pad.hooks) - 1; i >= 0; i-- {
			if pad.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pad *PostAttachmentDelete) ExecX(ctx context.Context) int {
	n, err := pad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pad *PostAttachmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: postattachment.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: postattachment.FieldID,
			},
		},
	}
	if ps := pad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pad.driver, _spec)
}

// PostAttachmentDeleteOne is the builder for deleting a single PostAttachment entity.
type PostAttachmentDeleteOne struct {
	pad *PostAttachmentDelete
}

// Exec executes the deletion query.
func (pado *PostAttachmentDeleteOne) Exec(ctx context.Context) error {
	n, err := pado.pad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{postattachment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pado *PostAttachmentDeleteOne) ExecX(ctx context.Context) {
	pado.pad.ExecX(ctx)
}
