// Code generated by entc, DO NOT EDIT.

package ent

import (
	"devlog/ent/admin"
	"devlog/ent/adminsession"
	"devlog/ent/category"
	"devlog/ent/post"
	"devlog/ent/postattachment"
	"devlog/ent/postimage"
	"devlog/ent/postthumbnail"
	"devlog/ent/postvideo"
	"devlog/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminFields := schema.Admin{}.Fields()
	_ = adminFields
	// adminDescEmail is the schema descriptor for email field.
	adminDescEmail := adminFields[0].Descriptor()
	// admin.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	admin.EmailValidator = adminDescEmail.Validators[0].(func(string) error)
	// adminDescUsername is the schema descriptor for username field.
	adminDescUsername := adminFields[1].Descriptor()
	// admin.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	admin.UsernameValidator = adminDescUsername.Validators[0].(func(string) error)
	// adminDescPassword is the schema descriptor for password field.
	adminDescPassword := adminFields[2].Descriptor()
	// admin.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	admin.PasswordValidator = adminDescPassword.Validators[0].(func(string) error)
	// adminDescJoinedAt is the schema descriptor for joined_at field.
	adminDescJoinedAt := adminFields[3].Descriptor()
	// admin.DefaultJoinedAt holds the default value on creation for the joined_at field.
	admin.DefaultJoinedAt = adminDescJoinedAt.Default.(func() time.Time)
	adminsessionFields := schema.AdminSession{}.Fields()
	_ = adminsessionFields
	// adminsessionDescToken is the schema descriptor for token field.
	adminsessionDescToken := adminsessionFields[0].Descriptor()
	// adminsession.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	adminsession.TokenValidator = adminsessionDescToken.Validators[0].(func(string) error)
	// adminsessionDescUsedAt is the schema descriptor for used_at field.
	adminsessionDescUsedAt := adminsessionFields[1].Descriptor()
	// adminsession.DefaultUsedAt holds the default value on creation for the used_at field.
	adminsession.DefaultUsedAt = adminsessionDescUsedAt.Default.(func() time.Time)
	// adminsessionDescCreatedAt is the schema descriptor for created_at field.
	adminsessionDescCreatedAt := adminsessionFields[2].Descriptor()
	// adminsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminsession.DefaultCreatedAt = adminsessionDescCreatedAt.Default.(func() time.Time)
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[0].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescDescription is the schema descriptor for description field.
	categoryDescDescription := categoryFields[1].Descriptor()
	// category.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	category.DescriptionValidator = categoryDescDescription.Validators[0].(func(string) error)
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryFields[2].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescModifiedAt is the schema descriptor for modified_at field.
	categoryDescModifiedAt := categoryFields[3].Descriptor()
	// category.DefaultModifiedAt holds the default value on creation for the modified_at field.
	category.DefaultModifiedAt = categoryDescModifiedAt.Default.(func() time.Time)
	// category.UpdateDefaultModifiedAt holds the default value on update for the modified_at field.
	category.UpdateDefaultModifiedAt = categoryDescModifiedAt.UpdateDefault.(func() time.Time)
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescUUID is the schema descriptor for uuid field.
	postDescUUID := postFields[0].Descriptor()
	// post.UUIDValidator is a validator for the "uuid" field. It is called by the builders before save.
	post.UUIDValidator = postDescUUID.Validators[0].(func(string) error)
	// postDescSlug is the schema descriptor for slug field.
	postDescSlug := postFields[1].Descriptor()
	// post.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	post.SlugValidator = postDescSlug.Validators[0].(func(string) error)
	// postDescTitle is the schema descriptor for title field.
	postDescTitle := postFields[3].Descriptor()
	// post.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	post.TitleValidator = postDescTitle.Validators[0].(func(string) error)
	// postDescPreviewContent is the schema descriptor for preview_content field.
	postDescPreviewContent := postFields[6].Descriptor()
	// post.PreviewContentValidator is a validator for the "preview_content" field. It is called by the builders before save.
	post.PreviewContentValidator = postDescPreviewContent.Validators[0].(func(string) error)
	// postDescCreatedAt is the schema descriptor for created_at field.
	postDescCreatedAt := postFields[7].Descriptor()
	// post.DefaultCreatedAt holds the default value on creation for the created_at field.
	post.DefaultCreatedAt = postDescCreatedAt.Default.(func() time.Time)
	// postDescModifiedAt is the schema descriptor for modified_at field.
	postDescModifiedAt := postFields[8].Descriptor()
	// post.DefaultModifiedAt holds the default value on creation for the modified_at field.
	post.DefaultModifiedAt = postDescModifiedAt.Default.(func() time.Time)
	// post.UpdateDefaultModifiedAt holds the default value on update for the modified_at field.
	post.UpdateDefaultModifiedAt = postDescModifiedAt.UpdateDefault.(func() time.Time)
	postattachmentFields := schema.PostAttachment{}.Fields()
	_ = postattachmentFields
	// postattachmentDescName is the schema descriptor for name field.
	postattachmentDescName := postattachmentFields[2].Descriptor()
	// postattachment.NameValidator is a validator for the "name" field. It is called by the builders before save.
	postattachment.NameValidator = postattachmentDescName.Validators[0].(func(string) error)
	// postattachmentDescMime is the schema descriptor for mime field.
	postattachmentDescMime := postattachmentFields[3].Descriptor()
	// postattachment.MimeValidator is a validator for the "mime" field. It is called by the builders before save.
	postattachment.MimeValidator = postattachmentDescMime.Validators[0].(func(string) error)
	// postattachmentDescURL is the schema descriptor for url field.
	postattachmentDescURL := postattachmentFields[4].Descriptor()
	// postattachment.URLValidator is a validator for the "url" field. It is called by the builders before save.
	postattachment.URLValidator = postattachmentDescURL.Validators[0].(func(string) error)
	// postattachmentDescCreatedAt is the schema descriptor for created_at field.
	postattachmentDescCreatedAt := postattachmentFields[5].Descriptor()
	// postattachment.DefaultCreatedAt holds the default value on creation for the created_at field.
	postattachment.DefaultCreatedAt = postattachmentDescCreatedAt.Default.(func() time.Time)
	postimageFields := schema.PostImage{}.Fields()
	_ = postimageFields
	// postimageDescHash is the schema descriptor for hash field.
	postimageDescHash := postimageFields[3].Descriptor()
	// postimage.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	postimage.HashValidator = postimageDescHash.Validators[0].(func(string) error)
	// postimageDescTitle is the schema descriptor for title field.
	postimageDescTitle := postimageFields[4].Descriptor()
	// postimage.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	postimage.TitleValidator = postimageDescTitle.Validators[0].(func(string) error)
	// postimageDescURL is the schema descriptor for url field.
	postimageDescURL := postimageFields[5].Descriptor()
	// postimage.URLValidator is a validator for the "url" field. It is called by the builders before save.
	postimage.URLValidator = postimageDescURL.Validators[0].(func(string) error)
	// postimageDescCreatedAt is the schema descriptor for created_at field.
	postimageDescCreatedAt := postimageFields[6].Descriptor()
	// postimage.DefaultCreatedAt holds the default value on creation for the created_at field.
	postimage.DefaultCreatedAt = postimageDescCreatedAt.Default.(func() time.Time)
	postthumbnailFields := schema.PostThumbnail{}.Fields()
	_ = postthumbnailFields
	// postthumbnailDescHash is the schema descriptor for hash field.
	postthumbnailDescHash := postthumbnailFields[2].Descriptor()
	// postthumbnail.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	postthumbnail.HashValidator = postthumbnailDescHash.Validators[0].(func(string) error)
	// postthumbnailDescURL is the schema descriptor for url field.
	postthumbnailDescURL := postthumbnailFields[3].Descriptor()
	// postthumbnail.URLValidator is a validator for the "url" field. It is called by the builders before save.
	postthumbnail.URLValidator = postthumbnailDescURL.Validators[0].(func(string) error)
	// postthumbnailDescCreatedAt is the schema descriptor for created_at field.
	postthumbnailDescCreatedAt := postthumbnailFields[4].Descriptor()
	// postthumbnail.DefaultCreatedAt holds the default value on creation for the created_at field.
	postthumbnail.DefaultCreatedAt = postthumbnailDescCreatedAt.Default.(func() time.Time)
	postvideoFields := schema.PostVideo{}.Fields()
	_ = postvideoFields
	// postvideoDescTitle is the schema descriptor for title field.
	postvideoDescTitle := postvideoFields[1].Descriptor()
	// postvideo.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	postvideo.TitleValidator = postvideoDescTitle.Validators[0].(func(string) error)
	// postvideoDescURL is the schema descriptor for url field.
	postvideoDescURL := postvideoFields[2].Descriptor()
	// postvideo.URLValidator is a validator for the "url" field. It is called by the builders before save.
	postvideo.URLValidator = postvideoDescURL.Validators[0].(func(string) error)
	// postvideoDescCreatedAt is the schema descriptor for created_at field.
	postvideoDescCreatedAt := postvideoFields[3].Descriptor()
	// postvideo.DefaultCreatedAt holds the default value on creation for the created_at field.
	postvideo.DefaultCreatedAt = postvideoDescCreatedAt.Default.(func() time.Time)
}
