// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"devlog/ent/predicate"
	"devlog/ent/unsavedpost"
	"devlog/ent/unsavedpostthumbnail"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UnsavedPostThumbnailQuery is the builder for querying UnsavedPostThumbnail entities.
type UnsavedPostThumbnailQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UnsavedPostThumbnail
	// eager-loading edges.
	withUnsavedPost *UnsavedPostQuery
	withFKs         bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UnsavedPostThumbnailQuery builder.
func (uptq *UnsavedPostThumbnailQuery) Where(ps ...predicate.UnsavedPostThumbnail) *UnsavedPostThumbnailQuery {
	uptq.predicates = append(uptq.predicates, ps...)
	return uptq
}

// Limit adds a limit step to the query.
func (uptq *UnsavedPostThumbnailQuery) Limit(limit int) *UnsavedPostThumbnailQuery {
	uptq.limit = &limit
	return uptq
}

// Offset adds an offset step to the query.
func (uptq *UnsavedPostThumbnailQuery) Offset(offset int) *UnsavedPostThumbnailQuery {
	uptq.offset = &offset
	return uptq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uptq *UnsavedPostThumbnailQuery) Unique(unique bool) *UnsavedPostThumbnailQuery {
	uptq.unique = &unique
	return uptq
}

// Order adds an order step to the query.
func (uptq *UnsavedPostThumbnailQuery) Order(o ...OrderFunc) *UnsavedPostThumbnailQuery {
	uptq.order = append(uptq.order, o...)
	return uptq
}

// QueryUnsavedPost chains the current query on the "unsaved_post" edge.
func (uptq *UnsavedPostThumbnailQuery) QueryUnsavedPost() *UnsavedPostQuery {
	query := &UnsavedPostQuery{config: uptq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uptq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uptq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(unsavedpostthumbnail.Table, unsavedpostthumbnail.FieldID, selector),
			sqlgraph.To(unsavedpost.Table, unsavedpost.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, unsavedpostthumbnail.UnsavedPostTable, unsavedpostthumbnail.UnsavedPostColumn),
		)
		fromU = sqlgraph.SetNeighbors(uptq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UnsavedPostThumbnail entity from the query.
// Returns a *NotFoundError when no UnsavedPostThumbnail was found.
func (uptq *UnsavedPostThumbnailQuery) First(ctx context.Context) (*UnsavedPostThumbnail, error) {
	nodes, err := uptq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{unsavedpostthumbnail.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uptq *UnsavedPostThumbnailQuery) FirstX(ctx context.Context) *UnsavedPostThumbnail {
	node, err := uptq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UnsavedPostThumbnail ID from the query.
// Returns a *NotFoundError when no UnsavedPostThumbnail ID was found.
func (uptq *UnsavedPostThumbnailQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uptq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{unsavedpostthumbnail.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uptq *UnsavedPostThumbnailQuery) FirstIDX(ctx context.Context) int {
	id, err := uptq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UnsavedPostThumbnail entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one UnsavedPostThumbnail entity is not found.
// Returns a *NotFoundError when no UnsavedPostThumbnail entities are found.
func (uptq *UnsavedPostThumbnailQuery) Only(ctx context.Context) (*UnsavedPostThumbnail, error) {
	nodes, err := uptq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{unsavedpostthumbnail.Label}
	default:
		return nil, &NotSingularError{unsavedpostthumbnail.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uptq *UnsavedPostThumbnailQuery) OnlyX(ctx context.Context) *UnsavedPostThumbnail {
	node, err := uptq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UnsavedPostThumbnail ID in the query.
// Returns a *NotSingularError when exactly one UnsavedPostThumbnail ID is not found.
// Returns a *NotFoundError when no entities are found.
func (uptq *UnsavedPostThumbnailQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uptq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{unsavedpostthumbnail.Label}
	default:
		err = &NotSingularError{unsavedpostthumbnail.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uptq *UnsavedPostThumbnailQuery) OnlyIDX(ctx context.Context) int {
	id, err := uptq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UnsavedPostThumbnails.
func (uptq *UnsavedPostThumbnailQuery) All(ctx context.Context) ([]*UnsavedPostThumbnail, error) {
	if err := uptq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return uptq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (uptq *UnsavedPostThumbnailQuery) AllX(ctx context.Context) []*UnsavedPostThumbnail {
	nodes, err := uptq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UnsavedPostThumbnail IDs.
func (uptq *UnsavedPostThumbnailQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := uptq.Select(unsavedpostthumbnail.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uptq *UnsavedPostThumbnailQuery) IDsX(ctx context.Context) []int {
	ids, err := uptq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uptq *UnsavedPostThumbnailQuery) Count(ctx context.Context) (int, error) {
	if err := uptq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return uptq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (uptq *UnsavedPostThumbnailQuery) CountX(ctx context.Context) int {
	count, err := uptq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uptq *UnsavedPostThumbnailQuery) Exist(ctx context.Context) (bool, error) {
	if err := uptq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return uptq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (uptq *UnsavedPostThumbnailQuery) ExistX(ctx context.Context) bool {
	exist, err := uptq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UnsavedPostThumbnailQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uptq *UnsavedPostThumbnailQuery) Clone() *UnsavedPostThumbnailQuery {
	if uptq == nil {
		return nil
	}
	return &UnsavedPostThumbnailQuery{
		config:          uptq.config,
		limit:           uptq.limit,
		offset:          uptq.offset,
		order:           append([]OrderFunc{}, uptq.order...),
		predicates:      append([]predicate.UnsavedPostThumbnail{}, uptq.predicates...),
		withUnsavedPost: uptq.withUnsavedPost.Clone(),
		// clone intermediate query.
		sql:  uptq.sql.Clone(),
		path: uptq.path,
	}
}

// WithUnsavedPost tells the query-builder to eager-load the nodes that are connected to
// the "unsaved_post" edge. The optional arguments are used to configure the query builder of the edge.
func (uptq *UnsavedPostThumbnailQuery) WithUnsavedPost(opts ...func(*UnsavedPostQuery)) *UnsavedPostThumbnailQuery {
	query := &UnsavedPostQuery{config: uptq.config}
	for _, opt := range opts {
		opt(query)
	}
	uptq.withUnsavedPost = query
	return uptq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Width uint32 `json:"width,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UnsavedPostThumbnail.Query().
//		GroupBy(unsavedpostthumbnail.FieldWidth).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (uptq *UnsavedPostThumbnailQuery) GroupBy(field string, fields ...string) *UnsavedPostThumbnailGroupBy {
	group := &UnsavedPostThumbnailGroupBy{config: uptq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := uptq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return uptq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Width uint32 `json:"width,omitempty"`
//	}
//
//	client.UnsavedPostThumbnail.Query().
//		Select(unsavedpostthumbnail.FieldWidth).
//		Scan(ctx, &v)
//
func (uptq *UnsavedPostThumbnailQuery) Select(field string, fields ...string) *UnsavedPostThumbnailSelect {
	uptq.fields = append([]string{field}, fields...)
	return &UnsavedPostThumbnailSelect{UnsavedPostThumbnailQuery: uptq}
}

func (uptq *UnsavedPostThumbnailQuery) prepareQuery(ctx context.Context) error {
	for _, f := range uptq.fields {
		if !unsavedpostthumbnail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uptq.path != nil {
		prev, err := uptq.path(ctx)
		if err != nil {
			return err
		}
		uptq.sql = prev
	}
	return nil
}

func (uptq *UnsavedPostThumbnailQuery) sqlAll(ctx context.Context) ([]*UnsavedPostThumbnail, error) {
	var (
		nodes       = []*UnsavedPostThumbnail{}
		withFKs     = uptq.withFKs
		_spec       = uptq.querySpec()
		loadedTypes = [1]bool{
			uptq.withUnsavedPost != nil,
		}
	)
	if uptq.withUnsavedPost != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, unsavedpostthumbnail.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UnsavedPostThumbnail{config: uptq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, uptq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := uptq.withUnsavedPost; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*UnsavedPostThumbnail)
		for i := range nodes {
			if nodes[i].unsaved_post_thumbnail == nil {
				continue
			}
			fk := *nodes[i].unsaved_post_thumbnail
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(unsavedpost.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "unsaved_post_thumbnail" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.UnsavedPost = n
			}
		}
	}

	return nodes, nil
}

func (uptq *UnsavedPostThumbnailQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uptq.querySpec()
	return sqlgraph.CountNodes(ctx, uptq.driver, _spec)
}

func (uptq *UnsavedPostThumbnailQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := uptq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (uptq *UnsavedPostThumbnailQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   unsavedpostthumbnail.Table,
			Columns: unsavedpostthumbnail.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: unsavedpostthumbnail.FieldID,
			},
		},
		From:   uptq.sql,
		Unique: true,
	}
	if unique := uptq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := uptq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, unsavedpostthumbnail.FieldID)
		for i := range fields {
			if fields[i] != unsavedpostthumbnail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uptq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uptq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uptq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uptq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uptq *UnsavedPostThumbnailQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uptq.driver.Dialect())
	t1 := builder.Table(unsavedpostthumbnail.Table)
	selector := builder.Select(t1.Columns(unsavedpostthumbnail.Columns...)...).From(t1)
	if uptq.sql != nil {
		selector = uptq.sql
		selector.Select(selector.Columns(unsavedpostthumbnail.Columns...)...)
	}
	for _, p := range uptq.predicates {
		p(selector)
	}
	for _, p := range uptq.order {
		p(selector)
	}
	if offset := uptq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uptq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UnsavedPostThumbnailGroupBy is the group-by builder for UnsavedPostThumbnail entities.
type UnsavedPostThumbnailGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uptgb *UnsavedPostThumbnailGroupBy) Aggregate(fns ...AggregateFunc) *UnsavedPostThumbnailGroupBy {
	uptgb.fns = append(uptgb.fns, fns...)
	return uptgb
}

// Scan applies the group-by query and scans the result into the given value.
func (uptgb *UnsavedPostThumbnailGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := uptgb.path(ctx)
	if err != nil {
		return err
	}
	uptgb.sql = query
	return uptgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uptgb *UnsavedPostThumbnailGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := uptgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (uptgb *UnsavedPostThumbnailGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(uptgb.fields) > 1 {
		return nil, errors.New("ent: UnsavedPostThumbnailGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := uptgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uptgb *UnsavedPostThumbnailGroupBy) StringsX(ctx context.Context) []string {
	v, err := uptgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uptgb *UnsavedPostThumbnailGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uptgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{unsavedpostthumbnail.Label}
	default:
		err = fmt.Errorf("ent: UnsavedPostThumbnailGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uptgb *UnsavedPostThumbnailGroupBy) StringX(ctx context.Context) string {
	v, err := uptgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (uptgb *UnsavedPostThumbnailGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(uptgb.fields) > 1 {
		return nil, errors.New("ent: UnsavedPostThumbnailGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := uptgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uptgb *UnsavedPostThumbnailGroupBy) IntsX(ctx context.Context) []int {
	v, err := uptgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uptgb *UnsavedPostThumbnailGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uptgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{unsavedpostthumbnail.Label}
	default:
		err = fmt.Errorf("ent: UnsavedPostThumbnailGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uptgb *UnsavedPostThumbnailGroupBy) IntX(ctx context.Context) int {
	v, err := uptgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (uptgb *UnsavedPostThumbnailGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(uptgb.fields) > 1 {
		return nil, errors.New("ent: UnsavedPostThumbnailGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := uptgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uptgb *UnsavedPostThumbnailGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := uptgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uptgb *UnsavedPostThumbnailGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uptgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{unsavedpostthumbnail.Label}
	default:
		err = fmt.Errorf("ent: UnsavedPostThumbnailGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uptgb *UnsavedPostThumbnailGroupBy) Float64X(ctx context.Context) float64 {
	v, err := uptgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (uptgb *UnsavedPostThumbnailGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(uptgb.fields) > 1 {
		return nil, errors.New("ent: UnsavedPostThumbnailGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := uptgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uptgb *UnsavedPostThumbnailGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := uptgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uptgb *UnsavedPostThumbnailGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uptgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{unsavedpostthumbnail.Label}
	default:
		err = fmt.Errorf("ent: UnsavedPostThumbnailGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uptgb *UnsavedPostThumbnailGroupBy) BoolX(ctx context.Context) bool {
	v, err := uptgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uptgb *UnsavedPostThumbnailGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range uptgb.fields {
		if !unsavedpostthumbnail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := uptgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uptgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uptgb *UnsavedPostThumbnailGroupBy) sqlQuery() *sql.Selector {
	selector := uptgb.sql
	columns := make([]string, 0, len(uptgb.fields)+len(uptgb.fns))
	columns = append(columns, uptgb.fields...)
	for _, fn := range uptgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(uptgb.fields...)
}

// UnsavedPostThumbnailSelect is the builder for selecting fields of UnsavedPostThumbnail entities.
type UnsavedPostThumbnailSelect struct {
	*UnsavedPostThumbnailQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (upts *UnsavedPostThumbnailSelect) Scan(ctx context.Context, v interface{}) error {
	if err := upts.prepareQuery(ctx); err != nil {
		return err
	}
	upts.sql = upts.UnsavedPostThumbnailQuery.sqlQuery(ctx)
	return upts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (upts *UnsavedPostThumbnailSelect) ScanX(ctx context.Context, v interface{}) {
	if err := upts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (upts *UnsavedPostThumbnailSelect) Strings(ctx context.Context) ([]string, error) {
	if len(upts.fields) > 1 {
		return nil, errors.New("ent: UnsavedPostThumbnailSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := upts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (upts *UnsavedPostThumbnailSelect) StringsX(ctx context.Context) []string {
	v, err := upts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (upts *UnsavedPostThumbnailSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = upts.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{unsavedpostthumbnail.Label}
	default:
		err = fmt.Errorf("ent: UnsavedPostThumbnailSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (upts *UnsavedPostThumbnailSelect) StringX(ctx context.Context) string {
	v, err := upts.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (upts *UnsavedPostThumbnailSelect) Ints(ctx context.Context) ([]int, error) {
	if len(upts.fields) > 1 {
		return nil, errors.New("ent: UnsavedPostThumbnailSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := upts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (upts *UnsavedPostThumbnailSelect) IntsX(ctx context.Context) []int {
	v, err := upts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (upts *UnsavedPostThumbnailSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = upts.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{unsavedpostthumbnail.Label}
	default:
		err = fmt.Errorf("ent: UnsavedPostThumbnailSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (upts *UnsavedPostThumbnailSelect) IntX(ctx context.Context) int {
	v, err := upts.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (upts *UnsavedPostThumbnailSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(upts.fields) > 1 {
		return nil, errors.New("ent: UnsavedPostThumbnailSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := upts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (upts *UnsavedPostThumbnailSelect) Float64sX(ctx context.Context) []float64 {
	v, err := upts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (upts *UnsavedPostThumbnailSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = upts.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{unsavedpostthumbnail.Label}
	default:
		err = fmt.Errorf("ent: UnsavedPostThumbnailSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (upts *UnsavedPostThumbnailSelect) Float64X(ctx context.Context) float64 {
	v, err := upts.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (upts *UnsavedPostThumbnailSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(upts.fields) > 1 {
		return nil, errors.New("ent: UnsavedPostThumbnailSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := upts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (upts *UnsavedPostThumbnailSelect) BoolsX(ctx context.Context) []bool {
	v, err := upts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (upts *UnsavedPostThumbnailSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = upts.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{unsavedpostthumbnail.Label}
	default:
		err = fmt.Errorf("ent: UnsavedPostThumbnailSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (upts *UnsavedPostThumbnailSelect) BoolX(ctx context.Context) bool {
	v, err := upts.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (upts *UnsavedPostThumbnailSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := upts.sqlQuery().Query()
	if err := upts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (upts *UnsavedPostThumbnailSelect) sqlQuery() sql.Querier {
	selector := upts.sql
	selector.Select(selector.Columns(upts.fields...)...)
	return selector
}
