// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"devlog/ent/predicate"
	"devlog/ent/unsavedpost"
	"devlog/ent/unsavedpostvideo"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UnsavedPostVideoQuery is the builder for querying UnsavedPostVideo entities.
type UnsavedPostVideoQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UnsavedPostVideo
	// eager-loading edges.
	withUnsavedPost *UnsavedPostQuery
	withFKs         bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UnsavedPostVideoQuery builder.
func (upvq *UnsavedPostVideoQuery) Where(ps ...predicate.UnsavedPostVideo) *UnsavedPostVideoQuery {
	upvq.predicates = append(upvq.predicates, ps...)
	return upvq
}

// Limit adds a limit step to the query.
func (upvq *UnsavedPostVideoQuery) Limit(limit int) *UnsavedPostVideoQuery {
	upvq.limit = &limit
	return upvq
}

// Offset adds an offset step to the query.
func (upvq *UnsavedPostVideoQuery) Offset(offset int) *UnsavedPostVideoQuery {
	upvq.offset = &offset
	return upvq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (upvq *UnsavedPostVideoQuery) Unique(unique bool) *UnsavedPostVideoQuery {
	upvq.unique = &unique
	return upvq
}

// Order adds an order step to the query.
func (upvq *UnsavedPostVideoQuery) Order(o ...OrderFunc) *UnsavedPostVideoQuery {
	upvq.order = append(upvq.order, o...)
	return upvq
}

// QueryUnsavedPost chains the current query on the "unsaved_post" edge.
func (upvq *UnsavedPostVideoQuery) QueryUnsavedPost() *UnsavedPostQuery {
	query := &UnsavedPostQuery{config: upvq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := upvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := upvq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(unsavedpostvideo.Table, unsavedpostvideo.FieldID, selector),
			sqlgraph.To(unsavedpost.Table, unsavedpost.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, unsavedpostvideo.UnsavedPostTable, unsavedpostvideo.UnsavedPostColumn),
		)
		fromU = sqlgraph.SetNeighbors(upvq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UnsavedPostVideo entity from the query.
// Returns a *NotFoundError when no UnsavedPostVideo was found.
func (upvq *UnsavedPostVideoQuery) First(ctx context.Context) (*UnsavedPostVideo, error) {
	nodes, err := upvq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{unsavedpostvideo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (upvq *UnsavedPostVideoQuery) FirstX(ctx context.Context) *UnsavedPostVideo {
	node, err := upvq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UnsavedPostVideo ID from the query.
// Returns a *NotFoundError when no UnsavedPostVideo ID was found.
func (upvq *UnsavedPostVideoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = upvq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{unsavedpostvideo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (upvq *UnsavedPostVideoQuery) FirstIDX(ctx context.Context) int {
	id, err := upvq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UnsavedPostVideo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one UnsavedPostVideo entity is not found.
// Returns a *NotFoundError when no UnsavedPostVideo entities are found.
func (upvq *UnsavedPostVideoQuery) Only(ctx context.Context) (*UnsavedPostVideo, error) {
	nodes, err := upvq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{unsavedpostvideo.Label}
	default:
		return nil, &NotSingularError{unsavedpostvideo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (upvq *UnsavedPostVideoQuery) OnlyX(ctx context.Context) *UnsavedPostVideo {
	node, err := upvq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UnsavedPostVideo ID in the query.
// Returns a *NotSingularError when exactly one UnsavedPostVideo ID is not found.
// Returns a *NotFoundError when no entities are found.
func (upvq *UnsavedPostVideoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = upvq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{unsavedpostvideo.Label}
	default:
		err = &NotSingularError{unsavedpostvideo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (upvq *UnsavedPostVideoQuery) OnlyIDX(ctx context.Context) int {
	id, err := upvq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UnsavedPostVideos.
func (upvq *UnsavedPostVideoQuery) All(ctx context.Context) ([]*UnsavedPostVideo, error) {
	if err := upvq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return upvq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (upvq *UnsavedPostVideoQuery) AllX(ctx context.Context) []*UnsavedPostVideo {
	nodes, err := upvq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UnsavedPostVideo IDs.
func (upvq *UnsavedPostVideoQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := upvq.Select(unsavedpostvideo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (upvq *UnsavedPostVideoQuery) IDsX(ctx context.Context) []int {
	ids, err := upvq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (upvq *UnsavedPostVideoQuery) Count(ctx context.Context) (int, error) {
	if err := upvq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return upvq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (upvq *UnsavedPostVideoQuery) CountX(ctx context.Context) int {
	count, err := upvq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (upvq *UnsavedPostVideoQuery) Exist(ctx context.Context) (bool, error) {
	if err := upvq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return upvq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (upvq *UnsavedPostVideoQuery) ExistX(ctx context.Context) bool {
	exist, err := upvq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UnsavedPostVideoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (upvq *UnsavedPostVideoQuery) Clone() *UnsavedPostVideoQuery {
	if upvq == nil {
		return nil
	}
	return &UnsavedPostVideoQuery{
		config:          upvq.config,
		limit:           upvq.limit,
		offset:          upvq.offset,
		order:           append([]OrderFunc{}, upvq.order...),
		predicates:      append([]predicate.UnsavedPostVideo{}, upvq.predicates...),
		withUnsavedPost: upvq.withUnsavedPost.Clone(),
		// clone intermediate query.
		sql:  upvq.sql.Clone(),
		path: upvq.path,
	}
}

// WithUnsavedPost tells the query-builder to eager-load the nodes that are connected to
// the "unsaved_post" edge. The optional arguments are used to configure the query builder of the edge.
func (upvq *UnsavedPostVideoQuery) WithUnsavedPost(opts ...func(*UnsavedPostQuery)) *UnsavedPostVideoQuery {
	query := &UnsavedPostQuery{config: upvq.config}
	for _, opt := range opts {
		opt(query)
	}
	upvq.withUnsavedPost = query
	return upvq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID string `json:"uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UnsavedPostVideo.Query().
//		GroupBy(unsavedpostvideo.FieldUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (upvq *UnsavedPostVideoQuery) GroupBy(field string, fields ...string) *UnsavedPostVideoGroupBy {
	group := &UnsavedPostVideoGroupBy{config: upvq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := upvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return upvq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID string `json:"uuid,omitempty"`
//	}
//
//	client.UnsavedPostVideo.Query().
//		Select(unsavedpostvideo.FieldUUID).
//		Scan(ctx, &v)
//
func (upvq *UnsavedPostVideoQuery) Select(field string, fields ...string) *UnsavedPostVideoSelect {
	upvq.fields = append([]string{field}, fields...)
	return &UnsavedPostVideoSelect{UnsavedPostVideoQuery: upvq}
}

func (upvq *UnsavedPostVideoQuery) prepareQuery(ctx context.Context) error {
	for _, f := range upvq.fields {
		if !unsavedpostvideo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if upvq.path != nil {
		prev, err := upvq.path(ctx)
		if err != nil {
			return err
		}
		upvq.sql = prev
	}
	return nil
}

func (upvq *UnsavedPostVideoQuery) sqlAll(ctx context.Context) ([]*UnsavedPostVideo, error) {
	var (
		nodes       = []*UnsavedPostVideo{}
		withFKs     = upvq.withFKs
		_spec       = upvq.querySpec()
		loadedTypes = [1]bool{
			upvq.withUnsavedPost != nil,
		}
	)
	if upvq.withUnsavedPost != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, unsavedpostvideo.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UnsavedPostVideo{config: upvq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, upvq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := upvq.withUnsavedPost; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*UnsavedPostVideo)
		for i := range nodes {
			if nodes[i].unsaved_post_videos == nil {
				continue
			}
			fk := *nodes[i].unsaved_post_videos
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(unsavedpost.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "unsaved_post_videos" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.UnsavedPost = n
			}
		}
	}

	return nodes, nil
}

func (upvq *UnsavedPostVideoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := upvq.querySpec()
	return sqlgraph.CountNodes(ctx, upvq.driver, _spec)
}

func (upvq *UnsavedPostVideoQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := upvq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (upvq *UnsavedPostVideoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   unsavedpostvideo.Table,
			Columns: unsavedpostvideo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: unsavedpostvideo.FieldID,
			},
		},
		From:   upvq.sql,
		Unique: true,
	}
	if unique := upvq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := upvq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, unsavedpostvideo.FieldID)
		for i := range fields {
			if fields[i] != unsavedpostvideo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := upvq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := upvq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := upvq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := upvq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (upvq *UnsavedPostVideoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(upvq.driver.Dialect())
	t1 := builder.Table(unsavedpostvideo.Table)
	selector := builder.Select(t1.Columns(unsavedpostvideo.Columns...)...).From(t1)
	if upvq.sql != nil {
		selector = upvq.sql
		selector.Select(selector.Columns(unsavedpostvideo.Columns...)...)
	}
	for _, p := range upvq.predicates {
		p(selector)
	}
	for _, p := range upvq.order {
		p(selector)
	}
	if offset := upvq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := upvq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UnsavedPostVideoGroupBy is the group-by builder for UnsavedPostVideo entities.
type UnsavedPostVideoGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (upvgb *UnsavedPostVideoGroupBy) Aggregate(fns ...AggregateFunc) *UnsavedPostVideoGroupBy {
	upvgb.fns = append(upvgb.fns, fns...)
	return upvgb
}

// Scan applies the group-by query and scans the result into the given value.
func (upvgb *UnsavedPostVideoGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := upvgb.path(ctx)
	if err != nil {
		return err
	}
	upvgb.sql = query
	return upvgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (upvgb *UnsavedPostVideoGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := upvgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (upvgb *UnsavedPostVideoGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(upvgb.fields) > 1 {
		return nil, errors.New("ent: UnsavedPostVideoGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := upvgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (upvgb *UnsavedPostVideoGroupBy) StringsX(ctx context.Context) []string {
	v, err := upvgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (upvgb *UnsavedPostVideoGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = upvgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{unsavedpostvideo.Label}
	default:
		err = fmt.Errorf("ent: UnsavedPostVideoGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (upvgb *UnsavedPostVideoGroupBy) StringX(ctx context.Context) string {
	v, err := upvgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (upvgb *UnsavedPostVideoGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(upvgb.fields) > 1 {
		return nil, errors.New("ent: UnsavedPostVideoGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := upvgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (upvgb *UnsavedPostVideoGroupBy) IntsX(ctx context.Context) []int {
	v, err := upvgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (upvgb *UnsavedPostVideoGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = upvgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{unsavedpostvideo.Label}
	default:
		err = fmt.Errorf("ent: UnsavedPostVideoGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (upvgb *UnsavedPostVideoGroupBy) IntX(ctx context.Context) int {
	v, err := upvgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (upvgb *UnsavedPostVideoGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(upvgb.fields) > 1 {
		return nil, errors.New("ent: UnsavedPostVideoGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := upvgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (upvgb *UnsavedPostVideoGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := upvgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (upvgb *UnsavedPostVideoGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = upvgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{unsavedpostvideo.Label}
	default:
		err = fmt.Errorf("ent: UnsavedPostVideoGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (upvgb *UnsavedPostVideoGroupBy) Float64X(ctx context.Context) float64 {
	v, err := upvgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (upvgb *UnsavedPostVideoGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(upvgb.fields) > 1 {
		return nil, errors.New("ent: UnsavedPostVideoGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := upvgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (upvgb *UnsavedPostVideoGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := upvgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (upvgb *UnsavedPostVideoGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = upvgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{unsavedpostvideo.Label}
	default:
		err = fmt.Errorf("ent: UnsavedPostVideoGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (upvgb *UnsavedPostVideoGroupBy) BoolX(ctx context.Context) bool {
	v, err := upvgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (upvgb *UnsavedPostVideoGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range upvgb.fields {
		if !unsavedpostvideo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := upvgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := upvgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (upvgb *UnsavedPostVideoGroupBy) sqlQuery() *sql.Selector {
	selector := upvgb.sql
	columns := make([]string, 0, len(upvgb.fields)+len(upvgb.fns))
	columns = append(columns, upvgb.fields...)
	for _, fn := range upvgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(upvgb.fields...)
}

// UnsavedPostVideoSelect is the builder for selecting fields of UnsavedPostVideo entities.
type UnsavedPostVideoSelect struct {
	*UnsavedPostVideoQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (upvs *UnsavedPostVideoSelect) Scan(ctx context.Context, v interface{}) error {
	if err := upvs.prepareQuery(ctx); err != nil {
		return err
	}
	upvs.sql = upvs.UnsavedPostVideoQuery.sqlQuery(ctx)
	return upvs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (upvs *UnsavedPostVideoSelect) ScanX(ctx context.Context, v interface{}) {
	if err := upvs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (upvs *UnsavedPostVideoSelect) Strings(ctx context.Context) ([]string, error) {
	if len(upvs.fields) > 1 {
		return nil, errors.New("ent: UnsavedPostVideoSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := upvs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (upvs *UnsavedPostVideoSelect) StringsX(ctx context.Context) []string {
	v, err := upvs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (upvs *UnsavedPostVideoSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = upvs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{unsavedpostvideo.Label}
	default:
		err = fmt.Errorf("ent: UnsavedPostVideoSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (upvs *UnsavedPostVideoSelect) StringX(ctx context.Context) string {
	v, err := upvs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (upvs *UnsavedPostVideoSelect) Ints(ctx context.Context) ([]int, error) {
	if len(upvs.fields) > 1 {
		return nil, errors.New("ent: UnsavedPostVideoSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := upvs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (upvs *UnsavedPostVideoSelect) IntsX(ctx context.Context) []int {
	v, err := upvs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (upvs *UnsavedPostVideoSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = upvs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{unsavedpostvideo.Label}
	default:
		err = fmt.Errorf("ent: UnsavedPostVideoSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (upvs *UnsavedPostVideoSelect) IntX(ctx context.Context) int {
	v, err := upvs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (upvs *UnsavedPostVideoSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(upvs.fields) > 1 {
		return nil, errors.New("ent: UnsavedPostVideoSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := upvs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (upvs *UnsavedPostVideoSelect) Float64sX(ctx context.Context) []float64 {
	v, err := upvs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (upvs *UnsavedPostVideoSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = upvs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{unsavedpostvideo.Label}
	default:
		err = fmt.Errorf("ent: UnsavedPostVideoSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (upvs *UnsavedPostVideoSelect) Float64X(ctx context.Context) float64 {
	v, err := upvs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (upvs *UnsavedPostVideoSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(upvs.fields) > 1 {
		return nil, errors.New("ent: UnsavedPostVideoSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := upvs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (upvs *UnsavedPostVideoSelect) BoolsX(ctx context.Context) []bool {
	v, err := upvs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (upvs *UnsavedPostVideoSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = upvs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{unsavedpostvideo.Label}
	default:
		err = fmt.Errorf("ent: UnsavedPostVideoSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (upvs *UnsavedPostVideoSelect) BoolX(ctx context.Context) bool {
	v, err := upvs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (upvs *UnsavedPostVideoSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := upvs.sqlQuery().Query()
	if err := upvs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (upvs *UnsavedPostVideoSelect) sqlQuery() sql.Querier {
	selector := upvs.sql
	selector.Select(selector.Columns(upvs.fields...)...)
	return selector
}
