// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"devlog/ent/predicate"
	"devlog/ent/unsavedpostthumbnail"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UnsavedPostThumbnailDelete is the builder for deleting a UnsavedPostThumbnail entity.
type UnsavedPostThumbnailDelete struct {
	config
	hooks    []Hook
	mutation *UnsavedPostThumbnailMutation
}

// Where adds a new predicate to the UnsavedPostThumbnailDelete builder.
func (uptd *UnsavedPostThumbnailDelete) Where(ps ...predicate.UnsavedPostThumbnail) *UnsavedPostThumbnailDelete {
	uptd.mutation.predicates = append(uptd.mutation.predicates, ps...)
	return uptd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uptd *UnsavedPostThumbnailDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uptd.hooks) == 0 {
		affected, err = uptd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UnsavedPostThumbnailMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uptd.mutation = mutation
			affected, err = uptd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uptd.hooks) - 1; i >= 0; i-- {
			mut = uptd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uptd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (uptd *UnsavedPostThumbnailDelete) ExecX(ctx context.Context) int {
	n, err := uptd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uptd *UnsavedPostThumbnailDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: unsavedpostthumbnail.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: unsavedpostthumbnail.FieldID,
			},
		},
	}
	if ps := uptd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, uptd.driver, _spec)
}

// UnsavedPostThumbnailDeleteOne is the builder for deleting a single UnsavedPostThumbnail entity.
type UnsavedPostThumbnailDeleteOne struct {
	uptd *UnsavedPostThumbnailDelete
}

// Exec executes the deletion query.
func (uptdo *UnsavedPostThumbnailDeleteOne) Exec(ctx context.Context) error {
	n, err := uptdo.uptd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{unsavedpostthumbnail.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uptdo *UnsavedPostThumbnailDeleteOne) ExecX(ctx context.Context) {
	uptdo.uptd.ExecX(ctx)
}
