// Code generated by entc, DO NOT EDIT.

package ent

import (
	"devlog/ent/unsavedpost"
	"devlog/ent/unsavedpostthumbnail"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// UnsavedPostThumbnail is the model entity for the UnsavedPostThumbnail schema.
type UnsavedPostThumbnail struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Width holds the value of the "width" field.
	Width *uint32 `json:"width,omitempty"`
	// Height holds the value of the "height" field.
	Height *uint32 `json:"height,omitempty"`
	// Hash holds the value of the "hash" field.
	Hash *string `json:"hash,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UnsavedPostThumbnailQuery when eager-loading is set.
	Edges                  UnsavedPostThumbnailEdges `json:"edges"`
	unsaved_post_thumbnail *int
}

// UnsavedPostThumbnailEdges holds the relations/edges for other nodes in the graph.
type UnsavedPostThumbnailEdges struct {
	// UnsavedPost holds the value of the unsaved_post edge.
	UnsavedPost *UnsavedPost `json:"unsaved_post,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UnsavedPostOrErr returns the UnsavedPost value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UnsavedPostThumbnailEdges) UnsavedPostOrErr() (*UnsavedPost, error) {
	if e.loadedTypes[0] {
		if e.UnsavedPost == nil {
			// The edge unsaved_post was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: unsavedpost.Label}
		}
		return e.UnsavedPost, nil
	}
	return nil, &NotLoadedError{edge: "unsaved_post"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UnsavedPostThumbnail) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case unsavedpostthumbnail.FieldID, unsavedpostthumbnail.FieldWidth, unsavedpostthumbnail.FieldHeight:
			values[i] = new(sql.NullInt64)
		case unsavedpostthumbnail.FieldHash:
			values[i] = new(sql.NullString)
		case unsavedpostthumbnail.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case unsavedpostthumbnail.ForeignKeys[0]: // unsaved_post_thumbnail
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type UnsavedPostThumbnail", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UnsavedPostThumbnail fields.
func (upt *UnsavedPostThumbnail) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case unsavedpostthumbnail.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			upt.ID = int(value.Int64)
		case unsavedpostthumbnail.FieldWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				upt.Width = new(uint32)
				*upt.Width = uint32(value.Int64)
			}
		case unsavedpostthumbnail.FieldHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				upt.Height = new(uint32)
				*upt.Height = uint32(value.Int64)
			}
		case unsavedpostthumbnail.FieldHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value.Valid {
				upt.Hash = new(string)
				*upt.Hash = value.String
			}
		case unsavedpostthumbnail.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				upt.CreatedAt = value.Time
			}
		case unsavedpostthumbnail.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field unsaved_post_thumbnail", value)
			} else if value.Valid {
				upt.unsaved_post_thumbnail = new(int)
				*upt.unsaved_post_thumbnail = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryUnsavedPost queries the "unsaved_post" edge of the UnsavedPostThumbnail entity.
func (upt *UnsavedPostThumbnail) QueryUnsavedPost() *UnsavedPostQuery {
	return (&UnsavedPostThumbnailClient{config: upt.config}).QueryUnsavedPost(upt)
}

// Update returns a builder for updating this UnsavedPostThumbnail.
// Note that you need to call UnsavedPostThumbnail.Unwrap() before calling this method if this UnsavedPostThumbnail
// was returned from a transaction, and the transaction was committed or rolled back.
func (upt *UnsavedPostThumbnail) Update() *UnsavedPostThumbnailUpdateOne {
	return (&UnsavedPostThumbnailClient{config: upt.config}).UpdateOne(upt)
}

// Unwrap unwraps the UnsavedPostThumbnail entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (upt *UnsavedPostThumbnail) Unwrap() *UnsavedPostThumbnail {
	tx, ok := upt.config.driver.(*txDriver)
	if !ok {
		panic("ent: UnsavedPostThumbnail is not a transactional entity")
	}
	upt.config.driver = tx.drv
	return upt
}

// String implements the fmt.Stringer.
func (upt *UnsavedPostThumbnail) String() string {
	var builder strings.Builder
	builder.WriteString("UnsavedPostThumbnail(")
	builder.WriteString(fmt.Sprintf("id=%v", upt.ID))
	if v := upt.Width; v != nil {
		builder.WriteString(", width=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := upt.Height; v != nil {
		builder.WriteString(", height=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := upt.Hash; v != nil {
		builder.WriteString(", hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", created_at=")
	builder.WriteString(upt.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UnsavedPostThumbnails is a parsable slice of UnsavedPostThumbnail.
type UnsavedPostThumbnails []*UnsavedPostThumbnail

func (upt UnsavedPostThumbnails) config(cfg config) {
	for _i := range upt {
		upt[_i].config = cfg
	}
}
