basePath: /v1
definitions:
  model.AdminCategory:
    properties:
      created-at:
        example: 2021-08-18 00:00:00Z
        type: string
      description:
        example: web-related things
        type: string
      modified-at:
        example: 2021-08-18 00:00:00Z
        type: string
      name:
        example: web
        type: string
    type: object
  model.HTTPError:
    properties:
      message:
        example: 500 - Internal Server Error
        type: string
    type: object
info:
  contact:
    email: led789zxpp@naver.com
    name: Author
    url: https://github.com/AcrylicShrimp
  description: A markdown-based lightweight blog service.
  license:
    name: MIT
  title: devlog
  version: 0.0.1
paths:
  /admin/categories:
    get:
      description: Lists all categories.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.AdminCategory'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
      summary: List categories
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Api-Token
    type: apiKey
swagger: "2.0"
