// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Admin is the predicate function for admin builders.
type Admin func(*sql.Selector)

// AdminSession is the predicate function for adminsession builders.
type AdminSession func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// PostImage is the predicate function for postimage builders.
type PostImage func(*sql.Selector)

// PostThumbnail is the predicate function for postthumbnail builders.
type PostThumbnail func(*sql.Selector)

// PostVideo is the predicate function for postvideo builders.
type PostVideo func(*sql.Selector)
